// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrmlyjjryrvppekmxecm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFybWx5ampyeXJ2cHBla214ZWNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTQwODMsImV4cCI6MjA1OTk3MDA4M30.gtX0IqvFUNqNgSlM-WJSh5jOgoSa6_4y1auGM9m1KoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);