name: 'Review with AI'
on: 
  pull_request:

jobs:
  review:
    permissions:
      models: read 
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create system prompt file
        run: |
          {
            echo "あなたはコードレビュワーAIです。"
            echo "以下のプロジェクト要件に基づいてコードレビューを行ってください。"
            echo ""
            echo "## コンポーネントアーキテクチャ"
            cat docs/requirement/00.components-architecture.md
            echo ""
            echo "## コードスタイル"
            cat docs/requirement/01.code-style.md
            echo ""
            echo "## Next.js ベストプラクティス"
            cat docs/requirement/02.next-bestpractice.md
            echo ""
            echo "上記の要件に基づいて、プルリクエストの変更内容を詳細にレビューし、改善点や問題点があれば具体的に指摘してください。"
          } > system-prompt.md

      - name: AI Review
        id: inference
        uses: actions/ai-inference@v1.1.0
        with:
          model: openai/gpt-4.1
          system-prompt-file: system-prompt.md
          prompt: |
            プルリクエストのタイトル: ${{ github.event.pull_request.title }}
            プルリクエストの本文: ${{ github.event.pull_request.body }}
          max-tokens: 60000

      - name: Comment on PR
        env:
          RESPONSE: ${{ steps.inference.outputs.response }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$RESPONSE" > comment.txt
          gh pr comment ${{ github.event.pull_request.number }} --body-file comment.txt